-- MySQL Script generated by MySQL Workbench
-- Sun Dec 22 17:13:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Trainee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Trainee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trainee` DEFAULT CHARACTER SET utf8 ;
USE `Trainee` ;

-- -----------------------------------------------------
-- Table `Trainee`.`Musculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trainee`.`Musculo` (
  `idMusculo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Grupo` ENUM('push', 'pull', 'leg') NOT NULL,
  PRIMARY KEY (`idMusculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trainee`.`Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trainee`.`Ejercicio` (
  `idEjercicio` INT NOT NULL,
  `mejorMarca` FLOAT NULL,
  `Musculo_idMusculo` INT NOT NULL,
  PRIMARY KEY (`idEjercicio`, `Musculo_idMusculo`),
  INDEX `fk_Ejercicio_Musculo1_idx` (`Musculo_idMusculo` ASC) VISIBLE,
  CONSTRAINT `fk_Ejercicio_Musculo1`
    FOREIGN KEY (`Musculo_idMusculo`)
    REFERENCES `Trainee`.`Musculo` (`idMusculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trainee`.`Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trainee`.`Serie` (
  `idSerie` INT NOT NULL,
  `peso` FLOAT NULL,
  `repeticiones` INT NULL,
  `completado` TINYINT NULL,
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trainee`.`EjercicioSerie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trainee`.`EjercicioSerie` (
  `idSerie` INT NOT NULL,
  `idEjercicio` INT NOT NULL,
  PRIMARY KEY (`idSerie`, `idEjercicio`),
  INDEX `fk_Serie_has_Ejercicio_Ejercicio1_idx` (`idEjercicio` ASC) VISIBLE,
  INDEX `fk_Serie_has_Ejercicio_Serie_idx` (`idSerie` ASC) VISIBLE,
  CONSTRAINT `fk_Serie_has_Ejercicio_Serie`
    FOREIGN KEY (`idSerie`)
    REFERENCES `Trainee`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serie_has_Ejercicio_Ejercicio1`
    FOREIGN KEY (`idEjercicio`)
    REFERENCES `Trainee`.`Ejercicio` (`idEjercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trainee`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trainee`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `peso` DOUBLE NULL,
  `idEntrenamiento` INT NULL,
  `idRutina` INT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trainee`.`Rutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trainee`.`Rutina` (
  `idRutina` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idRutina`, `idUsuario`),
  INDEX `fk_Rutina_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Rutina_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Trainee`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trainee`.`RutinaEjercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trainee`.`RutinaEjercicio` (
  `idRutina` INT NOT NULL,
  `dEjercicio` INT NOT NULL,
  PRIMARY KEY (`idRutina`, `dEjercicio`),
  INDEX `fk_Rutina_has_Ejercicio_Ejercicio1_idx` (`dEjercicio` ASC) VISIBLE,
  INDEX `fk_Rutina_has_Ejercicio_Rutina1_idx` (`idRutina` ASC) VISIBLE,
  CONSTRAINT `fk_Rutina_has_Ejercicio_Rutina1`
    FOREIGN KEY (`idRutina`)
    REFERENCES `Trainee`.`Rutina` (`idRutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rutina_has_Ejercicio_Ejercicio1`
    FOREIGN KEY (`dEjercicio`)
    REFERENCES `Trainee`.`Ejercicio` (`idEjercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trainee`.`Entrenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trainee`.`Entrenamiento` (
  `idEntrenamiento` INT NOT NULL,
  `fechaRealizacion` DATE NULL,
  `pesoTotal` FLOAT NULL,
  `idRutina` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEntrenamiento`, `idRutina`, `idUsuario`),
  INDEX `fk_Entrenamiento_Rutina1_idx` (`idRutina` ASC) VISIBLE,
  INDEX `fk_Entrenamiento_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Entrenamiento_Rutina1`
    FOREIGN KEY (`idRutina`)
    REFERENCES `Trainee`.`Rutina` (`idRutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrenamiento_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Trainee`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
